export const T = {
  bg:'#060B14', card:'#0F1924', border:'#1A2D4A', border2:'#243A5E',
  acc:'#2563EB', acl:'#3B82F6', acg:'rgba(37,99,235,.15)',
  grn:'#10B981', red:'#EF4444', ylw:'#F59E0B', prp:'#7C3AED',
  cyn:'#0891B2', gld:'#D97706',
  txt:'#F0F6FF', sub:'#94A3B8', muted:'#475569',
  surf:'#0D1626', alt:'#0A1120',
} as const;

export const CURRENCIES: Record<string,{symbol:string;name:string;rate:number;flag:string}> = {
  KRW:{symbol:'₩',name:'원',rate:1,flag:'🇰🇷'},
  USD:{symbol:'$',name:'달러',rate:0.000727,flag:'🇺🇸'},
  EUR:{symbol:'€',name:'유로',rate:0.000667,flag:'🇪🇺'},
  JPY:{symbol:'¥',name:'엔',rate:0.112,flag:'🇯🇵'},
  CNY:{symbol:'¥',name:'위안',rate:0.00527,flag:'🇨🇳'},
  GBP:{symbol:'£',name:'파운드',rate:0.000572,flag:'🇬🇧'},
  SGD:{symbol:'S$',name:'싱가폴달러',rate:0.000979,flag:'🇸🇬'},
  AED:{symbol:'د.إ',name:'디르함',rate:0.00267,flag:'🇦🇪'},
};

export const LANGS = [
  {code:'ko',name:'한국어',flag:'🇰🇷'},
  {code:'en',name:'English',flag:'🇺🇸'},
  {code:'ja',name:'日本語',flag:'🇯🇵'},
  {code:'zh',name:'中文',flag:'🇨🇳'},
  {code:'es',name:'Español',flag:'🇪🇸'},
];

export const I18N: Record<string,Record<string,string>> = {
  ko:{
    home:'홈',market:'시장',trading:'매매',auto:'자동',history:'일지',
    watchlist:'왓치리스트',backtest:'백테스트',ai:'AI',academy:'아카데미',
    settings:'설정',scanner:'스캐너',clock:'세계시장',heatmap:'히트맵',
    portfolio:'포트폴리오',alerts:'알림',social:'소셜',news:'뉴스',
    buy:'매수',sell:'매도',mock:'모의',live:'실전',more:'더보기',
    login:'로그인',logout:'로그아웃',signup:'회원가입',
    warning:'모의투자 기본값 · 수익 보장 없음 · 투자 손실은 본인 책임',
  },
  en:{
    home:'Home',market:'Market',trading:'Trade',auto:'Auto',history:'Journal',
    watchlist:'Watchlist',backtest:'Backtest',ai:'AI',academy:'Academy',
    settings:'Settings',scanner:'Scanner',clock:'Markets',heatmap:'Heatmap',
    portfolio:'Portfolio',alerts:'Alerts',social:'Social',news:'News',
    buy:'Buy',sell:'Sell',mock:'Paper',live:'Live',more:'More',
    login:'Login',logout:'Logout',signup:'Sign Up',
    warning:'Paper trading · No profit guarantee · Invest at your own risk',
  },
  ja:{
    home:'ホーム',market:'市場',trading:'取引',auto:'自動',history:'日誌',
    watchlist:'ウォッチ',backtest:'バックテスト',ai:'AI',academy:'学習',
    settings:'設定',scanner:'スキャン',clock:'市場時計',heatmap:'ヒートマップ',
    portfolio:'ポートフォリオ',alerts:'アラート',social:'ソーシャル',news:'ニュース',
    buy:'買い',sell:'売り',mock:'模擬',live:'実取引',more:'もっと',
    login:'ログイン',logout:'ログアウト',signup:'登録',
    warning:'模擬取引 · 利益保証なし · 投資は自己責任',
  },
  zh:{
    home:'首页',market:'市场',trading:'交易',auto:'自动',history:'日志',
    watchlist:'关注',backtest:'回测',ai:'AI',academy:'学习',
    settings:'设置',scanner:'扫描',clock:'市场时钟',heatmap:'热力图',
    portfolio:'投资组合',alerts:'提醒',social:'社交',news:'新闻',
    buy:'买入',sell:'卖出',mock:'模拟',live:'实盘',more:'更多',
    login:'登录',logout:'退出',signup:'注册',
    warning:'模拟交易 · 不保证盈利 · 投资风险自担',
  },
  es:{
    home:'Inicio',market:'Mercado',trading:'Operar',auto:'Auto',history:'Diario',
    watchlist:'Lista',backtest:'Backtest',ai:'IA',academy:'Academia',
    settings:'Ajustes',scanner:'Escáner',clock:'Mercados',heatmap:'Mapa',
    portfolio:'Cartera',alerts:'Alertas',social:'Social',news:'Noticias',
    buy:'Comprar',sell:'Vender',mock:'Demo',live:'Real',more:'Más',
    login:'Iniciar',logout:'Cerrar',signup:'Registrarse',
    warning:'Paper trading · Sin garantía de ganancias',
  },
};

export const WORLD_MARKETS = [
  {name:'뉴욕',flag:'🇺🇸',tz:'America/New_York',open:'09:30',close:'16:00',color:'#3B82F6'},
  {name:'서울',flag:'🇰🇷',tz:'Asia/Seoul',open:'09:00',close:'15:30',color:'#EF4444'},
  {name:'도쿄',flag:'🇯🇵',tz:'Asia/Tokyo',open:'09:00',close:'15:30',color:'#F59E0B'},
  {name:'런던',flag:'🇬🇧',tz:'Europe/London',open:'08:00',close:'16:30',color:'#8B5CF6'},
  {name:'홍콩',flag:'🇭🇰',tz:'Asia/Hong_Kong',open:'09:30',close:'16:00',color:'#DC2626'},
  {name:'코인',flag:'₿',tz:'UTC',open:'00:00',close:'24:00',color:'#F7931A'},
];

export const LOGO_SOURCES: Record<string,string> = {
  BTC:'https://assets.coingecko.com/coins/images/1/small/bitcoin.png',
  ETH:'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
  SOL:'https://assets.coingecko.com/coins/images/4128/small/solana.png',
  BNB:'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png',
  XRP:'https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png',
  DOGE:'https://assets.coingecko.com/coins/images/5/small/dogecoin.png',
  ADA:'https://assets.coingecko.com/coins/images/975/small/cardano.png',
  AVAX:'https://assets.coingecko.com/coins/images/12559/small/Avalanche_Circle_RedWhite_Trans.png',
  TON:'https://assets.coingecko.com/coins/images/17980/small/ton_symbol.png',
  LINK:'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png',
  DOT:'https://assets.coingecko.com/coins/images/12171/small/polkadot.png',
  MATIC:'https://assets.coingecko.com/coins/images/4713/small/matic-token-icon.png',
  SHIB:'https://assets.coingecko.com/coins/images/11939/small/shiba.png',
  ARB:'https://assets.coingecko.com/coins/images/16547/small/photo_2023-03-29_21.47.00.jpeg',
  OP:'https://assets.coingecko.com/coins/images/25244/small/Optimism.png',
  SUI:'https://assets.coingecko.com/coins/images/26375/small/sui_asset.jpeg',
  AAPL:'https://logo.clearbit.com/apple.com',
  MSFT:'https://logo.clearbit.com/microsoft.com',
  NVDA:'https://logo.clearbit.com/nvidia.com',
  TSLA:'https://logo.clearbit.com/tesla.com',
  AMZN:'https://logo.clearbit.com/amazon.com',
  GOOGL:'https://logo.clearbit.com/google.com',
  META:'https://logo.clearbit.com/meta.com',
  NFLX:'https://logo.clearbit.com/netflix.com',
  AMD:'https://logo.clearbit.com/amd.com',
  INTC:'https://logo.clearbit.com/intel.com',
  ORCL:'https://logo.clearbit.com/oracle.com',
  JPM:'https://logo.clearbit.com/jpmorganchase.com',
  WMT:'https://logo.clearbit.com/walmart.com',
  DIS:'https://logo.clearbit.com/disney.com',
  PLTR:'https://logo.clearbit.com/palantir.com',
  COIN:'https://logo.clearbit.com/coinbase.com',
  UBER:'https://logo.clearbit.com/uber.com',
  BABA:'https://logo.clearbit.com/alibaba.com',
  TSM:'https://logo.clearbit.com/tsmc.com',
  PYPL:'https://logo.clearbit.com/paypal.com',
  CRM:'https://logo.clearbit.com/salesforce.com',
  ADBE:'https://logo.clearbit.com/adobe.com',
  SHOP:'https://logo.clearbit.com/shopify.com',
  SNOW:'https://logo.clearbit.com/snowflake.com',
  NET:'https://logo.clearbit.com/cloudflare.com',
  CRWD:'https://logo.clearbit.com/crowdstrike.com',
  PANW:'https://logo.clearbit.com/paloaltonetworks.com',
  V:'https://logo.clearbit.com/visa.com',
  MA:'https://logo.clearbit.com/mastercard.com',
  GS:'https://logo.clearbit.com/goldmansachs.com',
  XOM:'https://logo.clearbit.com/exxonmobil.com',
  LLY:'https://logo.clearbit.com/lilly.com',
  JNJ:'https://logo.clearbit.com/jnj.com',
  UNH:'https://logo.clearbit.com/unitedhealthgroup.com',
  MCD:'https://logo.clearbit.com/mcdonalds.com',
  KO:'https://logo.clearbit.com/coca-cola.com',
  NKE:'https://logo.clearbit.com/nike.com',
  BA:'https://logo.clearbit.com/boeing.com',
  SEC:'https://logo.clearbit.com/samsung.com',
  SKH:'https://logo.clearbit.com/skhynix.com',
  NAVER:'https://logo.clearbit.com/navercorp.com',
  KAKAO:'https://logo.clearbit.com/kakao.com',
  LGE:'https://logo.clearbit.com/lg.com',
  HYUN:'https://logo.clearbit.com/hyundai.com',
  TYT:'https://logo.clearbit.com/toyota.com',
  SNY:'https://logo.clearbit.com/sony.com',
  SFT:'https://logo.clearbit.com/softbank.com',
  NTDO:'https://logo.clearbit.com/nintendo.com',
  BIDU:'https://logo.clearbit.com/baidu.com',
  TCEHY:'https://logo.clearbit.com/tencent.com',
  ASML:'https://logo.clearbit.com/asml.com',
  LVMH:'https://logo.clearbit.com/lvmh.com',
  SAP:'https://logo.clearbit.com/sap.com',
  QQQ:'https://logo.clearbit.com/invesco.com',
  SPY:'https://logo.clearbit.com/ssga.com',
  ARKK:'https://logo.clearbit.com/ark-invest.com',
  SOXL:'https://logo.clearbit.com/direxion.com',
};

export const MOCK_NEWS = [
  {id:'1',title:'비트코인 94,230,000원 돌파… 기관 매수세 강화',summary:'미국 현물 ETF에 3.2억 달러 순유입. 기관 매수 지속.',source:'CoinDesk',category:'코인',sentiment:'bullish',time:'5분 전'},
  {id:'2',title:'엔비디아 실적 어닝서프라이즈… 시간외 +4.1%',summary:'분기 매출이 시장 예상을 40% 초과. AI 수요 폭증.',source:'Reuters',category:'주식',sentiment:'bullish',time:'12분 전'},
  {id:'3',title:'연준 금리 동결 유지… 9월 인하 기대감 상승',summary:'파월 의장이 9월 인하 가능성을 시사. 달러 약세 전환.',source:'Bloomberg',category:'매크로',sentiment:'bullish',time:'28분 전'},
  {id:'4',title:'코스피 외국인 순매도 3,200억… 약세 흐름',summary:'원·달러 환율 상승으로 지수 약세. 반도체 업종 하락.',source:'연합뉴스',category:'국내',sentiment:'bearish',time:'45분 전'},
  {id:'5',title:'금값 사상 최고치 경신… 온스당 $3,420',summary:'안전자산 선호 심리와 달러 약세로 금값 급등.',source:'CNBC',category:'원자재',sentiment:'bullish',time:'1시간 전'},
  {id:'6',title:'이더리움 ETF 순유입 역대 최대 기록',summary:'기관 투자자들의 이더리움 ETF 매수세가 최고치를 기록.',source:'CoinGecko',category:'코인',sentiment:'bullish',time:'2시간 전'},
] as const;

export const ECON_EVENTS = [
  {date:'05-13',time:'21:30',event:'미국 소비자물가(CPI)',country:'🇺🇸',impact:'high',previous:'2.4%',forecast:'2.3%'},
  {date:'05-14',time:'장마감',event:'엔비디아 실적발표',country:'🇺🇸',impact:'high',previous:'$0.61',forecast:'$0.89'},
  {date:'05-28',time:'22:00',event:'FOMC 금리 결정',country:'🇺🇸',impact:'high',previous:'4.50%',forecast:'4.25%'},
  {date:'05-09',time:'21:30',event:'미국 비농업 고용(NFP)',country:'🇺🇸',impact:'high',previous:'228K',forecast:'135K'},
  {date:'05-08',time:'21:30',event:'미국 실업수당 청구',country:'🇺🇸',impact:'medium',previous:'241K',forecast:'238K'},
] as const;
