// src/lib/posters/meta.ts
// 40개 포스터에 type / difficulty / 핵심 요약 추가
// type → SVG 인디케이터 종류 결정

export type PosterType =
  | 'ichimoku' | 'rsi' | 'macd' | 'ema' | 'bollinger'
  | 'candle' | 'volume' | 'fibonacci'
  | 'entry' | 'risk' | 'psychology' | 'plan' | 'review' | 'generic';

export type Difficulty = 'beginner' | 'intermediate' | 'advanced';

export interface PosterMeta {
  type:        PosterType;
  difficulty:  Difficulty;
  summary?:    string;
  keypoints?:  string[];
  buyTiming?:  string;
  sellTiming?: string;
  tip?:        string;
}

export const DIFFICULTY_LABEL: Record<Difficulty, string> = {
  beginner:     '입문',
  intermediate: '중급',
  advanced:     '고급',
};

export const DIFFICULTY_COLOR: Record<Difficulty, string> = {
  beginner:     '#10B981',
  intermediate: '#F59E0B',
  advanced:     '#EF4444',
};

// 40개 포스터 메타 — 모두 keypoints/buyTiming/sellTiming/tip 채움
export const POSTER_META: Record<number, PosterMeta> = {
  1: {
    type: 'ichimoku', difficulty: 'intermediate',
    summary: '5개 선과 구름대로 추세·지지저항·반전을 동시에 본다',
    keypoints: [
      '전환선/기준선의 골든·데드 크로스',
      '구름대 위 = 강세, 구름대 아래 = 약세',
      '후행스팬으로 추세 확정 확인',
      '구름 두께 = 지지·저항 강도',
    ],
    buyTiming:  '전환선이 기준선을 상향 돌파 + 가격이 구름대 위',
    sellTiming: '전환선이 기준선을 하향 이탈 + 가격이 구름대 아래',
    tip: '신뢰도 ↑: 후행스팬이 26봉 전 가격 위에 있을 때',
  },
  2: { type: 'entry', difficulty: 'beginner',
    summary: '롱(매수) 진입의 5단계 체크리스트',
    keypoints: ['추세 확인','지지선 근접','거래량 증가','분할 진입','손절가 설정'],
    buyTiming: '주요 지지선 + 캔들 반전 + 거래량 증가 동시',
    sellTiming: '진입 근거 사라지면 즉시 청산 (지지선 이탈 등)',
    tip: '한 번에 전부 들어가지 말고 3분할 진입' },
  3: { type: 'entry', difficulty: 'beginner',
    summary: '숏(매도) 진입의 5단계 체크리스트',
    keypoints: ['하락 추세','저항선 거부','거래량 동반','분할 매도','손절가 설정'],
    buyTiming: '하락 추세 종료 신호 시 숏 청산 (매수 전환 아님)',
    sellTiming: '주요 저항선 + 캔들 거부 + 거래량 동반',
    tip: '숏은 변동성이 크니 작은 사이즈로' },
  4: { type: 'risk', difficulty: 'beginner',
    summary: '진입 전 손절·익절을 먼저 정하지 않으면 안 들어간다',
    keypoints: ['손익비 1:2 이상','손절은 직전 저점/고점','익절 분할','감정 매매 금지'],
    buyTiming: '진입가/손절가/익절가 세 가격이 정해져 있을 때만',
    sellTiming: '익절가 도달 → 분할 익절 / 손절가 터치 → 무조건 청산',
    tip: '손절가는 진입 전에 정한다. 진입 후엔 절대 옮기지 않는다' },
  5: { type: 'risk', difficulty: 'intermediate',
    summary: '레버리지 = 변동성 ÷ 청산까지의 여유',
    keypoints: ['1x = 100% 변동 가능','10x = 10% 변동 시 청산 위험','MMR 확인','펀딩비 코스트'],
    buyTiming: '낮은 변동성 + 명확한 추세에서만 레버리지 증가',
    sellTiming: '변동성 폭증 (VIX/ATR 증가) 시 레버리지 즉시 축소',
    tip: '레버리지는 신뢰도가 높을수록 작게. 손절 거리가 좁을수록 크게' },
  6: { type: 'ema', difficulty: 'beginner',
    summary: 'EMA20/60/120 배열로 추세 강도 측정',
    keypoints: ['정배열: 20>60>120 (강세)','역배열: 20<60<120 (약세)','EMA20이 60 위로 = 골든','거리 = 추세 강도'],
    buyTiming: 'EMA20이 EMA60 상향 돌파 (골든크로스)',
    sellTiming: 'EMA20이 EMA60 하향 이탈 (데드크로스)',
    tip: 'EMA 정배열 상태에서만 롱, 역배열에서만 숏' },
  7: { type: 'generic', difficulty: 'advanced',
    summary: '추세 전환 시그널 — 다이버전스 + 거래량 + 캔들 패턴',
    keypoints: ['고점/저점 이탈','RSI 다이버전스','거래량 폭발','반전 캔들'],
    buyTiming: '하락 추세 끝 + 강세 다이버전스 + 거래량 동반 반등 캔들',
    sellTiming: '상승 추세 끝 + 약세 다이버전스 + 거래량 동반 음봉',
    tip: '전환은 늦게 진입해도 늦지 않다 — 확인 후 진입' },
  8: { type: 'fibonacci', difficulty: 'intermediate',
    summary: '되돌림 23.6 / 38.2 / 50 / 61.8 / 78.6%',
    keypoints: ['주요 변곡점에서 그림','61.8%가 가장 강한 지지','78.6% 이탈시 추세 종료','확장 1.618/2.618은 익절 목표'],
    buyTiming: '상승 추세 중 38.2~61.8% 되돌림 후 반등 캔들',
    sellTiming: '하락 추세 중 38.2~61.8% 되돌림 후 거부 캔들',
    tip: '피보 단독 사용 X — 캔들 패턴 / 거래량과 함께' },
  9: { type: 'candle', difficulty: 'beginner',
    summary: '망치형·도지·장악형 등 반전 캔들 패턴',
    keypoints: ['망치형 = 하락 끝','역망치 = 반등 신호','도지 = 결정 보류','장악형 = 강한 반전'],
    buyTiming: '하락 추세 끝 + 망치형/장악형 출현 + 거래량 증가',
    sellTiming: '상승 추세 끝 + 슈팅스타/장악형 음봉 + 거래량 증가',
    tip: '캔들 단독 X — 지지/저항선과 결합해야 신뢰도 ↑' },
  10:{ type: 'generic', difficulty: 'beginner',
    summary: '여러 번 반등/저항받은 가격대 = 강한 지지/저항',
    keypoints: ['3회 이상 터치 = 신뢰','거래량 동반 시 강함','이탈하면 역할 반전','수평선 + 라운드 넘버'],
    buyTiming: '주요 지지선 터치 + 반등 캔들 (망치/장악형)',
    sellTiming: '주요 저항선 터치 + 거부 캔들 (슈팅스타/도지)',
    tip: '지지/저항 깨지면 역할 바뀜 — 깨진 저항은 새 지지' },
  11:{ type: 'generic', difficulty: 'beginner',
    summary: '고점 잇는 선 = 하락추세선, 저점 잇는 선 = 상승추세선',
    keypoints: ['최소 3점 연결','각도가 가파를수록 위험','이탈 = 추세 전환','평행 채널 형성 시 강함'],
    buyTiming: '상승 추세선 터치 + 반등 캔들',
    sellTiming: '하락 추세선 터치 + 거부 캔들',
    tip: '추세선 이탈은 추세 종료. 깊은 이탈 시 반대 진입 고려' },
  12:{ type: 'risk', difficulty: 'beginner',
    summary: '자본의 1~2%만 한 번에 위험 노출 (1% 룰)',
    keypoints: ['1회 손실 = 자본 × 1%','연속 10번 손실해도 10%만','계좌 보호 1순위','복리 효과는 살아남는 자에게'],
    buyTiming: '손절거리 × 사이즈 ≤ 자본 1%일 때만 진입',
    sellTiming: '한 자산 비중이 자본 20% 초과 시 일부 익절',
    tip: '"한 방"은 없다. 작게 자주 = 장기 생존' },
  13:{ type: 'psychology', difficulty: 'beginner',
    summary: '공포는 약손절을 만들고, 탐욕은 미익절을 만든다',
    keypoints: ['손절은 계획대로','익절은 분할로','뉴스에 흔들리지 마라','수익=보상, 손실=수수료'],
    buyTiming: '시장이 공포일 때 = 본인 분석대로 차분히 진입',
    sellTiming: '시장이 광기일 때 = 분할 익절 시작',
    tip: '진입 직전 30초 정지 — "이 거래의 근거는?" 자문' },
  14:{ type: 'plan', difficulty: 'beginner',
    summary: '진입 전 체크리스트 → 실행 → 복기 사이클',
    keypoints: ['시나리오 작성','진입/손절/익절 결정','실행 (감정 차단)','복기 (좋고나쁨 X, 사실만)'],
    buyTiming: '계획서에 적힌 조건 모두 충족 시',
    sellTiming: '계획서의 익절/손절 조건 충족 시',
    tip: '계획 없이 진입 = 도박. 매매일지 한 줄이라도 써라' },
  15:{ type: 'risk', difficulty: 'intermediate',
    summary: '계좌의 % 기반 사이즈 vs 절대 금액 사이즈',
    keypoints: ['리스크 = 손절거리 × 계약수','자본 ÷ (손절거리 × 1%) = 최대 계약수','켈리 공식 응용','분할 진입 권장'],
    buyTiming: '계산된 사이즈 ≤ 최대 허용 시',
    sellTiming: '사이즈가 누적돼 노출 한도 초과 시 일부 청산',
    tip: '신뢰도 70% 이상 거래만 풀 사이즈, 그 외는 1/2' },
  16:{ type: 'risk', difficulty: 'beginner',
    summary: '손익비 1:2 이상 거래만',
    keypoints: ['익절 / 손절 ≥ 2','승률 33%여도 흑자','감정 매매 차단','목표가 명확히 설정'],
    buyTiming: '직전 저항선 거리 ≥ 직전 지지선 거리 × 2',
    sellTiming: '1:1 도달 시 본전 손절로 이동, 1:2에서 분할 익절',
    tip: '손익비 < 2 거래는 아예 진입 안 함' },
  17:{ type: 'entry', difficulty: 'intermediate',
    summary: '목표가 = 직전 고점/저점 또는 측정된 패턴',
    keypoints: ['이전 저점/고점','피보나치 확장 1.618','측정된 패턴 (M/W)','라운드 넘버 (5000$)'],
    buyTiming: '진입 + 목표가까지 거리가 손절 거리의 2배 이상',
    sellTiming: '목표가 근접 + 추세 약화 신호 동반 시 분할 익절',
    tip: '목표가 못 정하면 진입도 못 한다 — 명확한 출구가 핵심' },
  18:{ type: 'risk', difficulty: 'intermediate',
    summary: '익절은 분할로 — 50% 1차 익절 후 본전 손절',
    keypoints: ['1:1 → 50% 익절','나머지 본전 손절','1:2 → 추가 50% 익절','잔여는 트레일링'],
    buyTiming: '계획상 익절 1차 도달 시 즉시 50% 분할 익절',
    sellTiming: '나머지 50%는 추세선/EMA 이탈까지 보유',
    tip: '전부 익절 vs 추가 보유 = 분할이 정답 (둘 다 일부 잡음)' },
  19:{ type: 'risk', difficulty: 'beginner',
    summary: '손절은 무조건. 옮기지 않는다',
    keypoints: ['진입 전 손절 설정','터치 시 즉시 청산','평균단가 낮추기 금지','수익권에서만 손절 위로 이동'],
    buyTiming: '손절가 위 가격에서만 추가 매수 고려',
    sellTiming: '손절가 터치 = 즉시 시장가 청산 (대기 금지)',
    tip: '손절가는 진입 전에 미리 설정. 진입 후엔 절대 변경 금지' },
  20:{ type: 'generic', difficulty: 'advanced',
    summary: '상승장 / 박스권 / 하락장별 전략',
    keypoints: ['상승장 = 추격매수','박스권 = 매물대 매매','하락장 = 짧은 반등 숏','시장 인식이 첫째'],
    buyTiming: '상승장: 눌림목 매수 / 박스권: 하단 지지 매수',
    sellTiming: '하락장: 반등 시 매도 / 박스권: 상단 저항 매도',
    tip: '내 전략이 어느 시장에서 통하는지 알기 — 만능 전략 없다' },
  21:{ type: 'review', difficulty: 'intermediate',
    summary: '매매일지 → 패턴 발견 → 전략 개선',
    keypoints: ['모든 거래 기록','승/패 이유 분석','월간 통계 작성','반복되는 실수 제거'],
    buyTiming: '복기에서 검증된 패턴만 진입',
    sellTiming: '복기에서 자주 놓친 익절 신호는 자동화',
    tip: '복기 안 하면 발전 없다. 손실 거래일수록 더 자세히' },
  22:{ type: 'psychology', difficulty: 'intermediate',
    summary: '연승·연패 모두 멘탈을 흔든다. 규칙으로 방어',
    keypoints: ['연승 후 사이즈 ↑ 위험','연패 후 보복매매 금지','일일 손실 한도','거래 휴식일'],
    buyTiming: '평소와 같은 사이즈로 진입 (연승해도 ↑ X)',
    sellTiming: '연패 3회 후 그날은 매매 중단',
    tip: '시장이 아니라 본인을 이기는 게임' },
  23:{ type: 'plan', difficulty: 'beginner',
    summary: '매일 같은 시간 / 같은 절차 = 일관된 결과',
    keypoints: ['시장 분석 → 시나리오 작성','진입 조건 확인','거래 실행','복기 및 다음 계획'],
    buyTiming: '루틴 시작 → 시나리오 작성 후 진입 시점',
    sellTiming: '루틴 종료 시간 → 미실행 거래는 다음날로',
    tip: '루틴 = 시스템. 시스템 있는 사람만 살아남는다' },
  24:{ type: 'psychology', difficulty: 'advanced',
    summary: '단기 손실보다 장기 복리. 1년 단위로 본다',
    keypoints: ['1일 ±10% 무시','월 수익률 추적','연간 손익곡선','복리 = 시간의 마법'],
    buyTiming: '장기 추세 강세 시 추가 비중 확대',
    sellTiming: '연간 목표 도달 시 일부 현금화',
    tip: '단기 변동성은 노이즈. 본인의 우위만 신뢰' },
  25:{ type: 'plan', difficulty: 'intermediate',
    summary: '진입 직전 7개 체크리스트',
    keypoints: ['추세','지지/저항','거래량','캔들 패턴','손익비','사이즈','시장 상황'],
    buyTiming: '7개 모두 ✓ 시에만 진입',
    sellTiming: '체크리스트 중 하나라도 X 되면 즉시 검토 후 청산',
    tip: '진입 직전 1분 정지. 체크리스트 빼먹지 마라' },
  26:{ type: 'volume', difficulty: 'beginner',
    summary: '거래량 = 가격의 신뢰도',
    keypoints: ['거래량 동반 상승 = 강함','거래량 없는 상승 = 약함','평균 대비 1.5배 ↑ = 관심','거래량 폭증 = 변곡점'],
    buyTiming: '돌파 + 거래량 평균 ≥ 2배 동반',
    sellTiming: '상승 중 거래량 감소 시작 시 일부 익절',
    tip: '가격은 거짓말해도 거래량은 거짓말 안 한다' },
  27:{ type: 'volume', difficulty: 'intermediate',
    summary: '가격은 신고가, 거래량은 줄어든다 = 약세 신호',
    keypoints: ['고점 다이버전스','저점 다이버전스','OBV 추세','매물대 두꺼움'],
    buyTiming: '하락 중 거래량 감소 + 가격 횡보 = 매도 압력 약화',
    sellTiming: '상승 중 거래량 감소 + 신고가 = 약세 다이버전스, 분할 매도',
    tip: '다이버전스는 즉시가 아닌 확인 후 진입 (1~2봉 대기)' },
  28:{ type: 'rsi', difficulty: 'intermediate',
    summary: 'RSI 30 이하 과매도, 70 이상 과매수',
    keypoints: [
      'RSI < 30 = 과매도 반등 가능',
      'RSI > 70 = 과매수 조정 가능',
      'RSI 다이버전스 = 강력한 신호',
      '추세장에서는 50선이 지지/저항',
    ],
    buyTiming:  'RSI가 30 이하에서 다시 30 상향 돌파',
    sellTiming: 'RSI가 70 이상에서 다시 70 하향 이탈',
    tip: '추세장에선 RSI 단독 사용 위험 — EMA/MACD와 함께' },
  29:{ type: 'macd', difficulty: 'intermediate',
    summary: 'MACD 선과 시그널선의 크로스로 추세 전환 포착',
    keypoints: [
      'MACD 선 > 시그널 = 매수',
      'MACD 선 < 시그널 = 매도',
      '히스토그램 = MACD - 시그널',
      '0선 위/아래 = 추세 방향',
    ],
    buyTiming:  '히스토그램이 음→양 전환 + MACD 0선 위',
    sellTiming: '히스토그램이 양→음 전환 + MACD 0선 아래',
    tip: '시그널은 후행지표 — 단독으로 쓰면 늦는다' },
  30:{ type: 'bollinger', difficulty: 'intermediate',
    summary: '20일 이동평균 ± 2 표준편차',
    keypoints: [
      '밴드 폭 좁아짐 = 돌파 임박',
      '상단 터치 후 안쪽 캔들 = 매도',
      '하단 터치 후 안쪽 캔들 = 매수',
      '추세장에선 밴드를 타고 간다',
    ],
    buyTiming: '하단 밴드 터치 후 안쪽으로 종가',
    sellTiming: '상단 밴드 터치 후 안쪽으로 종가',
    tip: '돌파 전 밴드 폭 (Bandwidth) 확인 필수' },
  31:{ type: 'generic', difficulty: 'intermediate',
    summary: '지지·저항의 실전 활용 — 매물대와 라운드 넘버',
    keypoints: ['매물대 두께','라운드 넘버','심리적 가격','이전 ATH/ATL'],
    buyTiming: '매물대 하단 진입 + 반등 캔들',
    sellTiming: '매물대 상단 거부 + 약세 캔들',
    tip: '매물대 깨지면 역할 반전 — 저항이 지지가 된다' },
  32:{ type: 'entry', difficulty: 'intermediate',
    summary: '추세선 + 거래량 + 캔들 패턴 조합',
    keypoints: ['추세선 터치','거래량 동반','반전 캔들','이전 변곡점 일치'],
    buyTiming: '상승 추세선 3차 터치 + 망치형 + 거래량',
    sellTiming: '추세선 이탈 + 거래량 폭증 = 즉시 청산',
    tip: '추세선은 그릴 때 객관적으로 — 끼워 맞추지 마라' },
  33:{ type: 'entry', difficulty: 'advanced',
    summary: '저항선 돌파 + 거래량 폭발 = 진입',
    keypoints: ['거래량 평균 ≥ 2배','종가 기준 돌파','리테스트 확인','분할 진입'],
    buyTiming: '저항선 종가 돌파 + 거래량 동반 (장중 돌파만은 X)',
    sellTiming: '돌파 후 다시 저항선 하향 시 즉시 청산 (가짜 돌파)',
    tip: '거래량 없는 돌파는 가짜 돌파일 확률 높음' },
  34:{ type: 'generic', difficulty: 'advanced',
    summary: '돌파 후 즉시 돌아오면 가짜 돌파',
    keypoints: ['거래량 부족','직후 회귀','피보나치 78.6 이탈','심리적 함정'],
    buyTiming: '진짜 돌파 확인 — 종가 + 거래량 + 리테스트 후 진입',
    sellTiming: '돌파 직후 회귀 시작 시 손절 (1~2봉 안에)',
    tip: '돌파 후 첫 봉이 음봉이면 의심 — 다음 봉까지 관찰' },
  35:{ type: 'psychology', difficulty: 'advanced',
    summary: '비트코인 4년 반감기 사이클',
    keypoints: ['반감기 = 공급 충격','반감기 후 12~18개월 강세','사이클 정점 → 80% 조정','3~4년 누적 매집'],
    buyTiming: '반감기 직후 + 강세장 초입에 누적 진입',
    sellTiming: '사이클 정점 신호 (펀딩비 폭증/극단 탐욕) 시 분할 매도',
    tip: '사이클은 거시적 가이드. 단기 매매와 별도 운용' },
  36:{ type: 'generic', difficulty: 'advanced',
    summary: 'BTC → ETH → 메이저 → 알트 순환',
    keypoints: ['BTC 도미넌스 추적','ETH/BTC 비율','시총 순서대로 자금 이동','후반 알트 펌프'],
    buyTiming: 'BTC 도미넌스 하락 + ETH/BTC 상승 = 알트 순환',
    sellTiming: '도미넌스 반등 시작 = 알트 매도 신호',
    tip: '순환 후반에 진입하면 늦는다 — 초중반에 합류' },
  37:{ type: 'psychology', difficulty: 'intermediate',
    summary: '공포·탐욕 지수, 펀딩비, 매수/매도 비율',
    keypoints: ['F&G < 20 = 극도 공포 (매수)','F&G > 80 = 극도 탐욕 (매도)','펀딩비 ±0.1% 극단','롱숏 비율'],
    buyTiming: 'F&G < 25 + 펀딩비 음수 = 역발상 매수 구간',
    sellTiming: 'F&G > 75 + 펀딩비 +0.1% 이상 = 과열 매도',
    tip: '시장 심리는 역발상의 도구. 극단에서만 작동' },
  38:{ type: 'psychology', difficulty: 'advanced',
    summary: '돌파 → 청산 → 회복 같은 세력 패턴',
    keypoints: ['Stop Hunt','Liquidity Sweep','심리적 가격대 공격','롱·숏 양쪽 청산'],
    buyTiming: '주요 저점 하향 돌파 후 즉시 회복 시 (Stop Hunt 후 반등)',
    sellTiming: '주요 고점 상향 돌파 후 즉시 회귀 시 (Liquidity Sweep)',
    tip: '청산 후 진입이 가장 안전. 청산 전 진입은 함정' },
  39:{ type: 'generic', difficulty: 'advanced',
    summary: '청산 히트맵으로 가격 흡인 지점 찾기',
    keypoints: ['청산 가격대 = 자석','대규모 OI 위치','롱 청산 가격 / 숏 청산 가격','시계열 추적'],
    buyTiming: '큰 숏 청산 클러스터 직전 (역발상)',
    sellTiming: '큰 롱 청산 클러스터 직전 (역발상)',
    tip: '청산맵은 보조 도구 — 차트 분석과 함께' },
  40:{ type: 'plan', difficulty: 'advanced',
    summary: '진입부터 청산까지 실전 시나리오 5개',
    keypoints: ['추세 추격','역추세 매매','박스권 매매','돌파 매매','뉴스 매매'],
    buyTiming: '시나리오별 진입 조건 모두 충족 시',
    sellTiming: '시나리오별 청산 조건 또는 손절 도달 시',
    tip: '한 시나리오만 잘하면 된다. 만능 전략 추구 금지' },
};

export function getPosterMeta(id: number): PosterMeta {
  return POSTER_META[id] || { type: 'generic', difficulty: 'beginner' };
}
